### PR TITLE
Run examples in Node 8.10.

### PR DESCRIPTION
**Pull request by ksaaskil**
- For some strange reason, running tests in `circleci/node:8.0` fails with `jsf.generate is not a function` but works fine in `circleci/node:8.10`, so use that for now.
- Tests also work fine locally when running `node:8.0`

### CODE REVIEW

**Comment by ksaaskil** [comment]
Apparently in Node 8.0 `json-schema-ref-parser@^3.1.2` gets installed, in my machine `json-schema-ref-parser@^6.0.2`, could be related, maybe.
